"""admin_auth_baseline

Revision ID: 55a628f2bb7d
Revises: cdfdaab4088e
Create Date: 2026-04-27 09:14:08.883372+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a628f2bb7d'
down_revision: Union[str, Sequence[str], None] = 'cdfdaab4088e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_login_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_code', sa.String(length=32), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("failure_code IS NULL OR failure_code IN ('WRONG_PASSWORD', 'USER_SUSPENDED', 'RATE_LIMITED', 'UNKNOWN_EMAIL')", name=op.f('ck_admin_login_attempts_failure_code_chk')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_login_attempts'))
    )
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('force_password_change_at', sa.DateTime(), nullable=True),
    sa.Column('last_password_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('super_admin')", name=op.f('ck_admin_users_role_chk')),
    sa.CheckConstraint("status IN ('active', 'suspended')", name=op.f('ck_admin_users_status_chk')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users')),
    sa.UniqueConstraint('email', name=op.f('uq_admin_users_email'))
    )
    op.create_table('admin_password_resets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=16), server_default='reset', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("purpose IN ('reset', 'invitation')", name=op.f('ck_admin_password_resets_purpose_chk')),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], name=op.f('fk_admin_password_resets_admin_user_id_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_password_resets')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_admin_password_resets_token_hash'))
    )
    op.create_table('admin_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('access_token_jti', sa.String(length=64), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('access_expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('access_expires_at > issued_at', name=op.f('ck_admin_sessions_access_after_issued_chk')),
    sa.CheckConstraint('refresh_expires_at > access_expires_at', name=op.f('ck_admin_sessions_refresh_after_access_chk')),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], name=op.f('fk_admin_sessions_admin_user_id_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_sessions')),
    sa.UniqueConstraint('access_token_jti', name=op.f('uq_admin_sessions_access_token_jti')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_admin_sessions_refresh_token_hash'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_sessions')
    op.drop_table('admin_password_resets')
    op.drop_table('admin_users')
    op.drop_table('admin_login_attempts')
    # ### end Alembic commands ###
