"""baseline

Revision ID: cdfdaab4088e
Revises: 
Create Date: 2026-04-27 02:31:43.378985+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # alembic autogenerate quirk: JSONB(astext_type=Text()) renders bare Text reference, manual import per STOP-4 α arbitration
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdfdaab4088e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_benchmark_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('target_llm', sa.String(length=64), nullable=True),
    sa.Column('total_brands', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_queries', sa.Integer(), server_default='0', nullable=True),
    sa.Column('avg_mention_rate', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('avg_geo_score', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('avg_sentiment', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('score_p25', sa.Float(), nullable=True),
    sa.Column('score_p50', sa.Float(), nullable=True),
    sa.Column('score_p75', sa.Float(), nullable=True),
    sa.Column('top_brands_json', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industry_benchmark_daily')),
    sa.UniqueConstraint('industry', 'date', 'target_llm', name='uq_industry_daily')
    )
    op.create_table('brand_mentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('brand_name', sa.String(length=256), nullable=False),
    sa.Column('product_name', sa.String(length=256), nullable=True),
    sa.Column('is_target', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('position_type', sa.String(length=32), nullable=True),
    sa.Column('position_rank', sa.Integer(), nullable=True),
    sa.Column('detail_level', sa.String(length=16), nullable=True),
    sa.Column('sentiment', sa.String(length=16), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('context_snippet', sa.Text(), nullable=True),
    sa.Column('mention_count', sa.Integer(), server_default='1', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_mentions')),
    sa.UniqueConstraint('response_id', 'brand_name', name='uq_mention_response_brand')
    )
    op.create_table('geo_score_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('target_llm', sa.String(length=64), nullable=True),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('total_queries', sa.Integer(), server_default='0', nullable=True),
    sa.Column('mention_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('mention_rate', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('avg_position_rank', sa.Float(), nullable=True),
    sa.Column('first_place_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('first_place_rate', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('positive_rate', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('negative_rate', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('avg_sentiment_score', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('citation_rate', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('avg_sov', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('avg_visibility', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('avg_sentiment', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('avg_sov_score', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('avg_citation_score', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('avg_geo_score', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('industry_rank', sa.Integer(), nullable=True),
    sa.Column('industry_sov_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geo_score_daily')),
    sa.UniqueConstraint('brand_id', 'date', 'target_llm', 'intent', 'language', name='uq_geo_daily_dims')
    )
    op.create_table('product_score_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('target_llm', sa.String(length=64), nullable=True),
    sa.Column('total_queries', sa.Integer(), server_default='0', nullable=True),
    sa.Column('mention_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('mention_rate', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('avg_position_rank', sa.Float(), nullable=True),
    sa.Column('first_place_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('first_place_rate', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('avg_sentiment_score', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('avg_geo_score', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('category_sov_pct', sa.Float(), nullable=True),
    sa.Column('category_rank', sa.Integer(), nullable=True),
    sa.Column('comparison_wins', sa.Integer(), server_default='0', nullable=True),
    sa.Column('comparison_total', sa.Integer(), server_default='0', nullable=True),
    sa.Column('win_rate', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('top_features_json', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('top_scenarios_json', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('price_positioning', sa.String(length=32), nullable=True),
    sa.Column('price_positioning_json', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('top_drivers_json', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_score_daily')),
    sa.UniqueConstraint('brand_id', 'product_name', 'date', 'target_llm', name='uq_product_daily')
    )
    op.create_table('response_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('dimension_industry', sa.String(length=128), nullable=True),
    sa.Column('dimension_company', sa.String(length=128), nullable=True),
    sa.Column('dimension_product', sa.String(length=128), nullable=True),
    sa.Column('dimension_category', sa.String(length=128), nullable=True),
    sa.Column('total_brands_mentioned', sa.Integer(), server_default='0', nullable=True),
    sa.Column('target_brand_mentioned', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('target_brand_position', sa.String(length=32), nullable=True),
    sa.Column('target_brand_rank', sa.Integer(), nullable=True),
    sa.Column('target_brand_sentiment', sa.String(length=16), nullable=True),
    sa.Column('target_brand_detail', sa.String(length=16), nullable=True),
    sa.Column('visibility_score', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('sentiment_score', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('sov_score', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('citation_score', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('geo_score', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('analyzer_model', sa.String(length=64), nullable=True),
    sa.Column('raw_analysis_json', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_response_analyses')),
    sa.UniqueConstraint('response_id', name=op.f('uq_response_analyses_response_id'))
    )
    op.create_table('citation_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('mention_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('citation_index', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['mention_id'], ['brand_mentions.id'], name=op.f('fk_citation_sources_mention_id_brand_mentions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citation_sources'))
    )
    op.create_table('product_feature_mentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=256), nullable=False),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('feature_name', sa.String(length=128), nullable=False),
    sa.Column('feature_sentiment', sa.String(length=16), nullable=True),
    sa.Column('context_snippet', sa.Text(), nullable=True),
    sa.Column('scenario', sa.String(length=128), nullable=True),
    sa.Column('price_positioning', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['response_analyses.id'], name=op.f('fk_product_feature_mentions_analysis_id_response_analyses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_feature_mentions'))
    )
    op.create_table('sentiment_drivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mention_id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=256), nullable=False),
    sa.Column('driver_text', sa.String(length=512), nullable=False),
    sa.Column('polarity', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('strength', sa.Float(), server_default='0.5', nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['mention_id'], ['brand_mentions.id'], name=op.f('fk_sentiment_drivers_mention_id_brand_mentions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentiment_drivers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentiment_drivers')
    op.drop_table('product_feature_mentions')
    op.drop_table('citation_sources')
    op.drop_table('response_analyses')
    op.drop_table('product_score_daily')
    op.drop_table('geo_score_daily')
    op.drop_table('brand_mentions')
    op.drop_table('industry_benchmark_daily')
    # ### end Alembic commands ###
