/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check if email exists and get auth method */
        post: operations["authLookup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register new user */
        post: operations["authRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify email address with token */
        get: operations["authVerifyEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset email */
        post: operations["authForgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password with token */
        post: operations["authResetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["authRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout user (revoke all sessions) */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Request account deletion (30-day window) */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create new project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project details */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /** Delete project */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /** Update project */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/v1/projects/{projectId}/competitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add competitor brand to project */
        post: operations["addCompetitor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/competitors/{brandId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove competitor brand from project */
        delete: operations["removeCompetitor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/brands/{brandId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get brand scoped to project */
        get: operations["getBrandScoped"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/brands/{brandId}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get brand metrics with optional profile group filtering */
        get: operations["getBrandMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List topics in project */
        get: operations["getTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/topics/{topicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete topic */
        delete: operations["deleteTopic"];
        options?: never;
        head?: never;
        /** Update topic (mark as keyword/ignored) */
        patch: operations["updateTopic"];
        trace?: never;
    };
    "/v1/projects/{projectId}/prompts/{promptId}/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get query executions for a prompt */
        get: operations["getQueryExecutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all profile groups */
        get: operations["getProfileGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/brands/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit new brand for discovery */
        post: operations["submitBrand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/brands/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List brand submissions (admin only) */
        get: operations["adminListSubmissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/brands/submissions/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve brand submission */
        post: operations["adminApproveBrand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/brands/submissions/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject brand submission */
        post: operations["adminRejectBrand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/brands/submissions/{id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge submission with existing brand */
        post: operations["adminMergeBrand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (admin only, paginated) */
        get: operations["adminListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit logs (admin only, paginated) */
        get: operations["adminAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/cost-dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cost events grouped by budget scope */
        get: operations["adminCostDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/profile-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List profile groups (admin view) */
        get: operations["adminListProfileGroups"];
        put?: never;
        /** Create profile group (admin only) */
        post: operations["adminCreateProfileGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/profile-groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update profile group (admin only) */
        patch: operations["adminUpdateProfileGroup"];
        trace?: never;
    };
    "/mcp/brands/{brandId}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Phase 2 — MCP skeleton only */
        get: operations["mcpBrandMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Phase 2 — MCP skeleton only */
        get: operations["mcpTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Project: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            name: string;
            /** Format: uuid */
            primaryBrandId: string;
            competitorBrandIds: string[];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ProjectInput: {
            name: string;
            /** Format: uuid */
            primaryBrandId: string;
        };
        Brand: {
            /** Format: uuid */
            id: string;
            nameZh: string;
            nameEn?: string;
            aliases?: string[];
            positioning?: string;
            priceRange?: string;
            origin?: string;
            /** @enum {string} */
            status: "active" | "inactive";
        };
        /** @description Brand view filtered by project scope (403 if not in scope) */
        BrandScoped: components["schemas"]["Brand"];
        CompetitorLink: {
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            brandId: string;
            /** Format: date-time */
            addedAt?: string;
        };
        Topic: {
            /** Format: uuid */
            id: string;
            text: string;
            dimension: string;
            isKeyword: boolean;
            isIgnored: boolean;
            status?: string;
        };
        Prompt: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            topicId: string;
            text: string;
            intent?: string;
        };
        /** @description Query with all profile group and execution context */
        ExecutableQuery: {
            /**
             * Format: uuid
             * @description Query ID for tracing
             */
            id: string;
            /** @description Complete user-facing prompt text */
            prompt: string;
            /** Format: uuid */
            promptId: string;
            /** @enum {string} */
            language: "zh-CN" | "en-US";
            /**
             * @description Intent always transported as string; stored as VARCHAR(50)
             * @enum {string}
             */
            intent: "informational" | "commercial" | "transactional" | "navigational";
            /** @description Empty array = any group; Profile-Aware sampling (DECISIONS §3) */
            profileGroupIds: string[];
            /**
             * @description true → PENDING if no account available (DECISIONS §4)
             * @default false
             */
            requiresLogin: boolean;
            /** @enum {string} */
            topicDimension: "品类" | "品牌" | "产品";
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Renamed from platform_query per DECISIONS §18 */
        QueryExecution: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            queryId: string;
            engineId: string;
            /** @enum {string} */
            status: "pending" | "running" | "success" | "failed";
            attempt: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            completedAt?: string;
        };
        AIResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            queryId: string;
            engineId: string;
            rawText: string;
            citations?: components["schemas"]["AIResponseCitation"][];
            latencyMs?: number;
            profile?: components["schemas"]["BrowserProfile"];
            sentiment?: number;
            /** @enum {string} */
            status?: "success" | "partial";
        };
        AIResponseCitation: {
            /** Format: uri */
            url: string;
            domain: string;
            /** Format: uuid */
            brandId?: string | null;
            confidence?: number;
            extractionMethod?: string;
        };
        BrandMetrics: {
            /** Format: uuid */
            brandId: string;
            mentionRate?: number;
            sentiment?: number;
            ranking?: number;
            shareOfVoice?: number;
            citationShare?: number;
            /** Format: date-time */
            periodStart?: string;
            /** Format: date-time */
            periodEnd?: string;
        };
        /** @description Browser profile instance per DECISIONS §14 */
        BrowserProfile: {
            /** @description Renamed from profileId (DECISIONS §14) */
            instanceId: string;
            profileGroupId: string;
            locale?: string;
            timezone?: string;
            userAgent?: string;
            platform?: string;
        };
        /** @description Profile group definition (DECISIONS §6, D-P1-6) */
        ProfileGroupResponse: {
            id: string;
            nameZh: string;
            nameEn: string;
            description?: string;
            industryScope?: string[] | null;
            isDefault: boolean;
        };
        BrandSubmissionInput: {
            brandNameZh: string;
            brandNameEn?: string;
            /** Format: uuid */
            industryId: string;
        };
        BrandSubmission: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            brandNameZh: string;
            brandNameEn?: string;
            /** @enum {string} */
            status: "pending" | "verified" | "approved" | "rejected" | "merged";
            llmVerificationResult?: Record<string, never>;
            rejectionReason?: string | null;
            /** Format: uuid */
            mergedIntoBrandId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ProfileGroupInput: {
            nameZh: string;
            nameEn: string;
            description?: string;
            industryScope?: string[];
        };
        AuditLog: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            actorId: string;
            action: string;
            resourceType?: string;
            resourceId?: string;
            changes?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Cost tracking with budget scope distinction (DECISIONS §13) */
        CostEvent: {
            /** Format: uuid */
            id: string;
            /**
             * @description Budget scope per DECISIONS §13
             * @enum {string}
             */
            budgetScope: "pipeline" | "kg";
            engineId?: string;
            costUsd: number;
            tokenCount?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description Adapter error codes (ADAPTER_CONTRACT §6) */
        AdapterError: {
            /** @enum {string} */
            code: "CAPTCHA_BLOCK" | "COOLDOWN" | "BANNED" | "FROZEN" | "TIMEOUT" | "NETWORK_ERROR" | "NO_ACCOUNT_AVAILABLE" | "PARSER_FAIL";
            message?: string;
        };
        Pagination: {
            page: number;
            pageSize: number;
            total: number;
            nextCursor?: string | null;
        };
        /** @description RFC 7807 error response format */
        ProblemDetails: {
            /** Format: uri */
            type?: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
        };
    };
    responses: {
        /** @description No Content */
        NoContent: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Bad Request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Too Many Requests */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        ProjectIdParam: string;
        PageParam: number;
        PageSizeParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authLookup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Email lookup result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        exists: boolean;
                        /** @enum {string} */
                        method: "password" | "sso";
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    authRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    name?: string;
                };
            };
        };
        responses: {
            /** @description User created; verification email sent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        userId: string;
                        verificationSent: boolean;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    authVerifyEmail: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        verified: boolean;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    authForgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            204: components["responses"]["NoContent"];
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    authResetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    password: string;
                };
            };
        };
        responses: {
            204: components["responses"]["NoContent"];
            400: components["responses"]["BadRequest"];
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login successful; refresh token in HttpOnly cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description JWT bearer token */
                        accessToken: string;
                        /** @description Refresh token (also in HttpOnly cookie) */
                        refreshToken: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    authRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken?: string;
                };
            };
        };
        responses: {
            /** @description New access token issued; refresh token rotated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken: string;
                        refreshToken: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    reason?: string;
                };
            };
        };
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Updated project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    addCompetitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    brandId: string;
                };
            };
        };
        responses: {
            /** @description Competitor link created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitorLink"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    removeCompetitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                brandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
        };
    };
    getBrandScoped: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                brandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Brand details (project-scoped) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandScoped"];
                };
            };
            /** @description Brand not in project scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getBrandMetrics: {
        parameters: {
            query?: {
                /** @description Comma-separated profile group IDs (empty = all groups) */
                profileGroups?: string;
                from?: string;
                to?: string;
                engine?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                brandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Brand metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandMetrics"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getTopics: {
        parameters: {
            query?: {
                status?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Topic list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"][];
                };
            };
        };
    };
    deleteTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
        };
    };
    updateTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    isKeyword?: boolean;
                    isIgnored?: boolean;
                };
            };
        };
        responses: {
            /** @description Updated topic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getQueryExecutions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                promptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Query execution list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryExecution"][];
                };
            };
        };
    };
    getProfileGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile group list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileGroupResponse"][];
                };
            };
        };
    };
    submitBrand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandSubmissionInput"];
            };
        };
        responses: {
            /** @description Submission created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandSubmission"];
                };
            };
        };
    };
    adminListSubmissions: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                pageSize?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submissions list (paginated) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["BrandSubmission"][];
                        pagination?: components["schemas"]["Pagination"];
                    };
                };
            };
        };
    };
    adminApproveBrand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submission approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandSubmission"];
                };
            };
        };
    };
    adminRejectBrand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Submission rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandSubmission"];
                };
            };
        };
    };
    adminMergeBrand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    targetBrandId: string;
                };
            };
        };
        responses: {
            /** @description Submission merged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandSubmission"];
                };
            };
        };
    };
    adminListUsers: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                pageSize?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["User"][];
                        pagination?: components["schemas"]["Pagination"];
                    };
                };
            };
        };
    };
    adminAuditLogs: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                pageSize?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["AuditLog"][];
                        pagination?: components["schemas"]["Pagination"];
                    };
                };
            };
        };
    };
    adminCostDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cost events grouped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostEvent"][];
                };
            };
        };
    };
    adminListProfileGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile groups list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileGroupResponse"][];
                };
            };
        };
    };
    adminCreateProfileGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileGroupInput"];
            };
        };
        responses: {
            /** @description Profile group created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileGroupResponse"];
                };
            };
        };
    };
    adminUpdateProfileGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileGroupInput"];
            };
        };
        responses: {
            /** @description Updated profile group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileGroupResponse"];
                };
            };
        };
    };
    mcpBrandMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Brand metrics for MCP */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandMetrics"];
                };
            };
        };
    };
    mcpTopics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Topics list for MCP */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"][];
                };
            };
        };
    };
}
