"""Topic-analysis sub-package — split from the legacy
`_topic_analysis_service.py` god-module.

This package is being filled incrementally; see Epic #885 and tracking issue
#887. Public surface re-exported here for backwards-compatible imports.
"""

from __future__ import annotations

from app.api.v1.projects.topic_analysis.fact_rollup import (
    _bucket_position,
    _fact_all_mention_count,
    _fact_brand_scope_matched,
    _fact_target_mention_count,
    _logical_query_key,
    _row_attempt_sort_key,
    _row_attempt_time,
)
from app.api.v1.projects.topic_analysis.filters import (
    DEFAULT_WINDOW_DAYS,
    AnalysisFilters,
    _is_non_branded_row,
    _mention_name_condition,
    _prompt_scope_from_row,
    _resolve_window,
    _row_matches_analysis_filters,
    _target_mention_condition,
    _text_scope_conditions,
)
from app.api.v1.projects.topic_analysis.legacy_schema import (
    _not_deleted_condition,
    _prompt_scope_expr,
    _prompt_tags_expr,
    _prompt_text_expr,
    _safe_ident,
    _select_col,
    _topic_name_expr,
    legacy_table_columns,
    legacy_table_exists,
)
from app.api.v1.projects.topic_analysis.normalize import (
    _as_float,
    _as_int,
    _coerce_json,
    _date_key,
    _iso,
    _mean,
    _normalize_key,
    _pct,
    _response_preview,
    _round,
    _timestamp_key,
)
from app.api.v1.projects.topic_analysis.profiles import (
    _brand_fact_terms,
    _clean_fact_term,
    _expand_brand_fact_terms,
    _profile_name,
    _profile_names_for_ids,
    _profile_names_for_rows,
)
from app.api.v1.projects.topic_analysis.queries import (
    _dt_range,
    _engine_conditions,
    _fact_rows,
    _false_condition,
    _has_admin_chain,
    _query_scope_conditions,
    _query_text_expr,
    _response_latest_order_sql,
    _response_text_expr,
    _success_status_condition,
)

__all__ = [
    "DEFAULT_WINDOW_DAYS",
    "AnalysisFilters",
    "_as_float",
    "_as_int",
    "_brand_fact_terms",
    "_bucket_position",
    "_clean_fact_term",
    "_coerce_json",
    "_date_key",
    "_dt_range",
    "_engine_conditions",
    "_expand_brand_fact_terms",
    "_fact_all_mention_count",
    "_fact_brand_scope_matched",
    "_fact_rows",
    "_fact_target_mention_count",
    "_false_condition",
    "_has_admin_chain",
    "_is_non_branded_row",
    "_iso",
    "_logical_query_key",
    "_mean",
    "_mention_name_condition",
    "_normalize_key",
    "_not_deleted_condition",
    "_pct",
    "_profile_name",
    "_profile_names_for_ids",
    "_profile_names_for_rows",
    "_prompt_scope_expr",
    "_prompt_scope_from_row",
    "_prompt_tags_expr",
    "_prompt_text_expr",
    "_query_scope_conditions",
    "_query_text_expr",
    "_resolve_window",
    "_response_latest_order_sql",
    "_response_preview",
    "_response_text_expr",
    "_round",
    "_row_attempt_sort_key",
    "_row_attempt_time",
    "_row_matches_analysis_filters",
    "_safe_ident",
    "_select_col",
    "_success_status_condition",
    "_target_mention_condition",
    "_text_scope_conditions",
    "_timestamp_key",
    "_topic_name_expr",
    "legacy_table_columns",
    "legacy_table_exists",
]
